name: Application CI/CD & Security Scan

on:
  push:
    branches:
      - master
    paths:
      - "example-voting-app"
      - ".github/workflows/app-deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: codebuild-eks-deploy-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push images to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          for app in vote result worker; do
            ECR_REPOSITORY="example-${app}-app"
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./example-voting-app/${app}
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          done

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 1. Update Kubeconfig
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name voting-app-cluster

          # 2. Enter the k8s directory
          cd k8s

          # 3. Safely swap target images for ALL apps
          kustomize edit set image example-vote-app=$ECR_REGISTRY/example-vote-app:$IMAGE_TAG
          kustomize edit set image example-result-app=$ECR_REGISTRY/example-result-app:$IMAGE_TAG
          kustomize edit set image example-worker-app=$ECR_REGISTRY/example-worker-app:$IMAGE_TAG

          # 4. Apply all manifests at once atomically
          kubectl apply -k .

          # 5. Restart all deployments
          kubectl rollout restart deployment/vote deployment/result deployment/worker
