name: Terragrunt Plan & Security

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
      - ".github/workflows/infra-plan.yml"
      - ".github/workflows/infra-apply.yml"
jobs:
  terragrunt-plan:
    runs-on: codebuild-eks-deploy-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "1.0.4"
          tf_path: "terraform"

      - name: Run Trivy Scanner (IaC)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "config"
          scan-ref: "./infra"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
          trivyignores: ".trivyignore.yaml"

      - name: Hydrate env.yaml
        working-directory: ./infra
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          ALERT_EMAIL: ${{ secrets.YOUR_EMAIL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          cat <<EOF > env.yaml
          aws_region: "$AWS_REGION"
          cloudflare_api_token: "$CLOUDFLARE_API_TOKEN"
          github_pat: "$GH_PAT"
          github_repo_url: "https://github.com/${{ github.repository }}.git"
          # Dummy IP: Since the runner is INSIDE the VPC, it uses internal routing. This just satisfies the Terraform variable requirement.
          local_workstation_cidr: "203.0.113.0/24"
          alert_email_address: "$ALERT_EMAIL"
          cloudflare_account_id: "$CLOUDFLARE_ACCOUNT_ID"
          cloudflare_zone_id: "$CLOUDFLARE_ZONE_ID"
          domain_name: "$DOMAIN_NAME"
          EOF

      - name: Terragrunt Run-All Plan
        working-directory: ./infra
        run: terragrunt run --all --non-interactive plan
